# Site settings
title: Sean Kenny
email: sean.kenny@hotmail.com
description: >
    Various ramblings. All to be taken with a pinch of salt.
baseurl: ""
url: "https://cookiefission.github.io"
twitter_username: cookiefission
github_username: cookiefission

# Build settings
markdown: kramdown
permalink: pretty
