# Site settings
title: Sean Kenny
email: sean.kenny@hotmail.com
description: >
    Various ramblings. All to be taken with a pinch of salt.
baseurl: ""
url: "https://sean-kenny.github.io"
twitter_username: sean_kenny_
github_username: sean-kenny

# Build settings
markdown: kramdown
permalink: pretty
